name: Publish Package to NPM

on:
  release:
    types: [created] # Sadece GitHub'da bir "Release" (Sürüm) yayınlandığında çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      
      # Bağımlılıkları kurar
      - run: npm ci
      
      # Paketi NPM'de yayınlar
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      # Başarılı olduğunda Discord Webhook'a mesaj atar
      - name: Discord Notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: '🚀 **Lumis Framework** paketi başarıyla güncellendi! Yeni sürümü indirebilirsiniz.'
